import{a as q,S as O,i}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const R="https://pixabay.com/api/",$="50819756-11248eda55a36e78284ebe321",B=15,m=async(s,r=1)=>{const o={key:$,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:B};try{return(await q.get(R,{params:o})).data}catch{throw new Error("Oops! Something went wrong. Please try again later.")}},h=document.querySelector(".gallery"),g=document.querySelector(".loader"),y=document.querySelector(".load-more-button"),E=new O(".gallery a",{captionsData:"alt",captionDelay:250}),f=s=>{const r=s.map(({webformatURL:o,largeImageURL:a,tags:e,likes:t,views:n,comments:S,downloads:P})=>`
    <li class="gallery-item">
    <a href="${a}">
    <img src="${o}" alt="${e}"/>
    </a>
    <div class="info">
    <p class="properties">Likes <span class="value">${t}</span></p>
    <p class="properties">Views <span class="value">${n}</span></p>
    <p class="properties">Comments <span class="value">${S}</span></p>
    <p class="properties">Downloads <span class="value">${P}</span></p>
    </div>

    </li>`).join("");h.insertAdjacentHTML("beforeend",r),E.refresh()},M=()=>{h.innerHTML=""},L=()=>{g.classList.remove("hidden")},v=()=>{g.classList.add("hidden")},w=()=>{y.classList.remove("hidden")},c=()=>{y.classList.add("hidden")},b=document.querySelector(".form"),u=b.elements["search-text"],x=document.querySelector(".load-more-button");let d="",l=1,p=0;b.addEventListener("submit",async s=>{s.preventDefault();const r=u.value.trim();if(!r){i.error({message:"Please enter a search term!",position:"topRight"});return}M(),c(),L(),d=r,l=1;try{const o=await m(d,l);if(p=o.totalHits,!o.hits.length){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}f(o.hits),p>o.hits.length&&w()}catch{i.error({message:"Oops! Something went wrong. Please try again later.",position:"topRight"})}finally{v(),u.value=""}});x.addEventListener("click",async()=>{l+=1,L(),c();try{const s=await m(d,l);f(s.hits);const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),document.querySelectorAll(".gallery-item").length>=p?(c(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch{i.error({message:"Failed to load more images.",position:"topRight"})}finally{v()}});
//# sourceMappingURL=index.js.map
